import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createSystemHarness} from '../support/system-harness.mjs';
import {decodeBackupZip} from '../../src/shared/zip.ts';
const login=async(page:any)=>{expect((await page.request.post('/api/v1/auth/login',{data:{username:'browser-test',password:process.env.JSONBIN_TEST_PASSWORD}})).status()).toBe(200);};
test('设置路由刷新、并发保存草稿和创建时默认',async({page})=>{
 await login(page);await page.goto('/');const nav=page.getByRole('button',{name:'设置',exact:true});await expect(nav).toBeEnabled();await nav.click();await expect(page).toHaveURL(/#\/settings$/);await expect(page.getByRole('heading',{name:'系统信息',exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('默认可见性')).toBeVisible();
 await page.getByLabel('默认可见性').selectOption('public');await page.getByLabel('默认 TTL（秒）').fill('60');await page.getByRole('button',{name:'保存默认设置',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'默认设置已保存'})).toBeVisible();
 const saved=await(await page.request.get('/api/v1/system/settings')).json();await page.getByLabel('默认 TTL（秒）').fill('90');await page.request.patch('/api/v1/system/settings',{headers:{'If-Match':saved.etag},data:{defaultTtlSeconds:120}});await page.getByRole('button',{name:'保存默认设置',exact:true}).click();await expect(page.getByRole('alert')).toContainText('草稿已保留');await expect(page.getByLabel('默认 TTL（秒）')).toHaveValue('90');page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'数据仓',exact:true}).click();await expect(page).toHaveURL(/#\/settings$/);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'重新读取设置',exact:true}).click();await expect(page.getByLabel('默认 TTL（秒）')).toHaveValue('120');await page.getByRole('button',{name:'数据仓',exact:true}).click();await page.getByRole('button',{name:'新建数据仓',exact:true}).first().click();const dialog=page.getByRole('dialog');await dialog.getByLabel('名称',{exact:true}).fill('默认创建');await dialog.getByRole('button',{name:'新建数据仓',exact:true}).click();await expect(page.locator('.bin-detail')).toBeVisible();const id=page.url().split('/').at(-1)!;const bin=await(await page.request.get('/api/v1/bins/'+id)).json();expect(bin.meta.visibility).toBe('public');expect(bin.meta.expiresAt).not.toBeNull();
 const current=await(await page.request.get('/api/v1/system/settings')).json();await page.request.patch('/api/v1/system/settings',{headers:{'If-Match':current.etag},data:{defaultVisibility:'private',defaultTtlSeconds:null}});
});
test('真实普通文件预览、模式区分和部分失败',async({page})=>{
 await login(page);await page.goto('/#/settings');const imports=page.locator('.import-panel');await imports.getByLabel('选择导入文件').setInputFiles([{name:'空.json',mimeType:'application/json',buffer:Buffer.from('\ufeffnull')},{name:'数组.json',mimeType:'application/json',buffer:Buffer.from('[1,2]')},{name:'普通.json',mimeType:'application/json',buffer:Buffer.from('{"format":"jsonbin-backup"}')}]);await expect(imports).toContainText('3 个文件');await expect(imports).toContainText('空值');await expect(imports).toContainText('数组');
 let posted=false;page.on('request',req=>{if(req.url().endsWith('/system/import'))posted=true;});expect(posted).toBe(false);
 const h=await createSystemHarness('browser-partial-'+crypto.randomUUID());try {
 let metas=0;await page.route('**/api/v1/system/import',async route=>{const req=route.request(),headers=new Headers(req.headers());headers.set('Cookie',h.cookie);const response=await h.worker.fetch(new Request(req.url(),{method:'POST',headers,body:req.postDataBuffer()}),{...h.env,APP_ORIGIN:new URL(req.url()).origin,DATA:h.adapt({put:async(key,...args)=>{if(key.startsWith('bins/')&&key.endsWith('/meta.json')&&++metas===2)throw Error('test-fault');return h.bucket.put(key,...args);}})});await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});
 await imports.getByRole('button',{name:'确认导入',exact:true}).click();await expect(imports).toContainText('创建成功');await expect(imports).toContainText('失败');expect(posted).toBe(true);
 await imports.getByLabel('选择导入文件').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from([255])});await expect(imports.getByRole('alert')).toContainText('格式');}finally{await h.close();}
});
test('真实 Worker ZIP 下载迁移到独立空存储，恢复历史并保留原 ID',async({page})=>{
 const source=await createSystemHarness('browser-source-'+crypto.randomUUID()),destination=await createSystemHarness('browser-destination-'+crypto.randomUUID());let current=source;
 try{
  const bin=await(await source.request('/bins',{method:'POST',value:{name:'备份往返',value:{中文:false},visibility:'public'}})).json();await source.request('/bins/'+bin.meta.id,{method:'PUT',headers:{'If-Match':bin.etag},value:{value:null}});
  const expired=await(await source.request('/bins',{method:'POST',value:{name:'过期提示',value:false}})).json();const key=`bins/${expired.meta.id}/meta.json`,meta=await(await source.bucket.get(key)).json();await source.bucket.put(key,JSON.stringify({...meta,expiresAt:'2000-01-01T00:00:00.000Z'}));
  await page.route('**/api/v1/**',async route=>{const req=route.request(),headers={...req.headers(),Cookie:current.cookie};const response=await current.worker.fetch(new Request(req.url(),{method:req.method(),headers,...(['GET','HEAD'].includes(req.method())?{}:{body:req.postDataBuffer()})}),{...current.env,APP_ORIGIN:new URL(req.url()).origin});await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});
  await page.goto('/#/settings');const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出全部业务 ZIP',exact:true}).click();const artifact=await download,path=await artifact.path();expect(path).not.toBeNull();const bytes=await readFile(path!);const backup=await decodeBackupZip(new Uint8Array(bytes));expect(backup.bins.length).toBe(2);expect(backup.bins.find(b=>b.meta.id===bin.meta.id)?.versions.length).toBe(2);
  current=destination;await page.reload();const imports=page.locator('.import-panel');await imports.getByLabel('导入模式').selectOption('backup');await imports.getByLabel('选择导入文件').setInputFiles({name:'backup.zip',mimeType:'application/zip',buffer:bytes});await expect(imports).toContainText('公开资源：1');await expect(imports).toContainText('已到期：1');await imports.getByRole('button',{name:'确认恢复',exact:true}).click();await expect(imports).toContainText('恢复处理完成');
  const restored=await(await destination.request('/bins/'+bin.meta.id)).json();expect(restored.value).toBeNull();expect(restored.meta.currentVersion).toBe(2);const history=await(await destination.request('/bins/'+bin.meta.id+'/versions')).json();expect(history.items.length).toBe(2);expect((await(await destination.request('/trash/bins')).json()).items.length).toBe(1);
 }finally{await page.unrouteAll({behavior:'wait'});await source.close();await destination.close();}
});
test('导出已保存 JSON 保留设置草稿，移动端深色无横向溢出',async({page})=>{
 await login(page);const bin=await(await page.request.post('/api/v1/bins',{data:{name:'导出草稿',value:{saved:'中文'}}})).json();await page.goto('/#/bins/'+bin.meta.id);await page.getByRole('tab',{name:'设置',exact:true}).click();await page.getByLabel('名称',{exact:true}).fill('未保存');const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出已保存 JSON',exact:true}).click();const path=await(await download).path();expect(JSON.parse(await readFile(path!,'utf8'))).toEqual({saved:'中文'});await expect(page.getByLabel('名称',{exact:true})).toHaveValue('未保存');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'设置',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'切换明暗主题'}).click();await expect(page.locator('html')).toHaveClass(/dark/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('停止读取与改选文件丢弃迟到结果',async({page})=>{
 await login(page);await page.addInitScript(()=>{const original=File.prototype.arrayBuffer;const pending:Record<string,()=>void>={};(window as any).pendingFiles=pending;File.prototype.arrayBuffer=function(){if(this.name.startsWith('slow'))return new Promise<ArrayBuffer>(resolve=>{pending[this.name]=()=>{original.call(this).then(resolve);};});return original.call(this);};});
 await page.goto('/#/settings');const panel=page.locator('.import-panel');await panel.getByLabel('选择导入文件').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from('null')});await expect(panel.getByRole('button',{name:'确认导入',exact:true})).toBeDisabled();await panel.getByRole('button',{name:'停止等待',exact:true}).click();await expect(panel.getByRole('status')).toContainText('停止');await page.evaluate(()=>(window as any).pendingFiles['slow.json']());await expect(panel).not.toContainText('slow.json');
 await panel.getByLabel('选择导入文件').setInputFiles({name:'slow2.json',mimeType:'application/json',buffer:Buffer.from('false')});await panel.getByLabel('选择导入文件').setInputFiles({name:'new.json',mimeType:'application/json',buffer:Buffer.from('[]')});await expect(panel).toContainText('new.json');await page.evaluate(()=>(window as any).pendingFiles['slow2.json']());await expect(panel).not.toContainText('slow2.json');await expect(panel).toContainText('数组');
});
test('离页和退出后的慢导出不触发下载',async({page})=>{
 await login(page);let release:()=>void=()=>{};await page.route('**/api/v1/system/export?*',async route=>{await new Promise<void>(resolve=>{release=resolve;});try{await route.fulfill({status:200,contentType:'application/json',body:'null'});}catch{/* Aborted browser request. */}});
 await page.goto('/#/settings');let downloads=0;page.on('download',()=>downloads++);await page.getByRole('button',{name:'导出配置 JSON',exact:true}).click();await expect(page.getByRole('button',{name:'导出配置 JSON',exact:true})).toBeDisabled();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'概览',exact:true}).click();release();await expect(page).toHaveURL(/#\/$/);expect(downloads).toBe(0);
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'导出配置 JSON',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'退出登录',exact:true}).click();release();await expect(page.getByRole('heading',{name:'欢迎回来',exact:true})).toBeVisible();expect(downloads).toBe(0);
});
test('默认设置不可读时导入预览明确显示未知',async({page})=>{
 await login(page);await page.route('**/api/v1/system/settings',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"settings_unavailable"}'}));await page.goto('/#/settings');const panel=page.locator('.import-panel');await panel.getByLabel('选择导入文件').setInputFiles({name:'raw.json',mimeType:'application/json',buffer:Buffer.from('null')});await expect(panel).toContainText('默认值暂不可用');
});
test('迟到默认值不覆盖手动选择，明确永不过期优先',async({page})=>{
 await login(page);const old=await(await page.request.get('/api/v1/system/settings')).json();await page.request.patch('/api/v1/system/settings',{headers:{'If-Match':old.etag},data:{defaultVisibility:'public',defaultTtlSeconds:60}});let release:()=>void=()=>{};await page.route('**/api/v1/system/settings',async route=>{const response=await route.fetch();await new Promise<void>(resolve=>{release=resolve;});await route.fulfill({response});});await page.goto('/#/bins');await page.getByRole('button',{name:'新建数据仓',exact:true}).first().click();const dialog=page.getByRole('dialog');await dialog.getByLabel('名称',{exact:true}).fill('明确默认');await dialog.getByRole('combobox',{name:'可见性',exact:true}).selectOption('private');await dialog.getByLabel('到期策略').selectOption('never');release();await expect(dialog.getByRole('combobox',{name:'可见性',exact:true})).toHaveValue('private');await expect(dialog.getByLabel('到期策略')).toHaveValue('never');await dialog.getByRole('button',{name:'新建数据仓',exact:true}).click();await expect(page.locator('.bin-detail')).toBeVisible();const id=page.url().split('/').at(-1)!;const bin=await(await page.request.get('/api/v1/bins/'+id)).json();expect(bin.meta.visibility).toBe('private');expect(bin.meta.expiresAt).toBeNull();const settings=await(await page.request.get('/api/v1/system/settings')).json();await page.request.patch('/api/v1/system/settings',{headers:{'If-Match':settings.etag},data:{defaultVisibility:'private',defaultTtlSeconds:null}});
});
