import type { DocOperation, DocScope, DocSection, DocError } from './types.ts';
export const DOC_SCOPES: readonly DocScope[] = ['bin:read','bin:create','bin:update','bin:delete','collection:read','collection:write','schema:read','schema:write','history:read'];
export const DEMO_VALUE = { settings: { theme: 'light' }, enabled: false, note: null };
export const DOC_SECTIONS: readonly DocSection[] = [
  {id:'search',title:'全局搜索与索引',introduction:['GET /search 按名称、描述和资源 UUID 搜索数据仓、集合、模型，不检索 JSON 正文。q trim 后 1–160 字符；type=all|bin|collection|schema（默认 all），limit=1–50（默认 20）；未知、重复和错误参数返回 400。Bin 也匹配集合名称或 ID。', '全部搜索需要 bin:read + collection:read + schema:read；Bin 搜索需要 bin:read + collection:read；集合或模型筛选只需各自 read。即使 Bin 公开也不开放匿名搜索，显式 Authorization 不回退 Cookie。', '返回 {items,nextCursor,source}，items 只含当前可用的元数据摘要；source=kv|r2。下一页传 cursor 并保留 q/type/limit；资源变化返回 409 search_changed，应从第一页重查。最多扫描 10000 个 R2 对象 / 200 个资源，超限返回 503 search_limit_exceeded，不返回部分结果。', 'KV 是可丢弃的派生索引，缺失、过期、损坏或不可用时回退 R2。GET /search/index、POST /search/rebuild 仅允许管理 Session，任何 Authorization 都拒绝；重建不修改业务 JSON。KV 未配置或写失败为 503，重建中资源变化为 409。每次最多清理 200 个废弃索引，503 search_cleanup_limit_exceeded 时再次重建继续。设置页提供重建入口。']},
  {id:'auth',title:'登录与认证',introduction:['API 基础路径为 /api/v1。网页登录使用 HttpOnly、HTTPS Secure、SameSite=Lax Session Cookie，有效期 14 天；登录、退出和受 Session 保护的写入均检查浏览器 Origin。登录正文实际 UTF-8 字节上限 4 KiB；未配置有效 SESSION_SECRET 返回 503。','外部调用使用 Authorization: Bearer <API_TOKEN>。显式 Authorization 不回退到 Cookie：Token 无效返回 401，权限不足返回 403。CORS 默认仅允许请求站点自身；配置 APP_ORIGIN 时仅允许该完整 http(s) Origin（无路径或末尾斜杠），错误配置拒绝跨站来源。curl/Python 可不发送 Origin，但仍须认证。','所有 API 响应 no-store；ETag、X-JSONBin-Version、X-Request-ID 对允许的浏览器来源可读。curl Session 示例先运行登录命令保存 cookies.txt；Python 先执行登录示例创建 session，后续管理请求复用同一个 session；JavaScript Session 示例在已登录的同站浏览器中使用 credentials: include。']},
  {id:'keys',title:'API Key 与权限',introduction:['在 API 密钥页面创建 Token。新建密钥的完整 Token 会使用 SESSION_SECRET 派生的加密密钥保存，可在登录后的密钥页面重新显示或复制；旧版本创建且没有加密明文的密钥仍可认证，但无法恢复完整值。为外部调用赋予所需的最小 Scope；不要在共享示例中填写真实密钥。','密钥管理仅允许管理 Session，所有 Authorization（即使 Cookie 有效）都返回 session_required。恢复历史/回收站需要 bin:update + history:read；读取集合成员需要 collection:read + bin:read。']},
  {id:'bins',title:'Bin CRUD',introduction:['演示资源 UUID、<API_TOKEN>、<ETAG>、<USERNAME>、<PASSWORD> 都需要替换；通用代码使用固定演示 JSON。','普通读取返回 meta/value/etag，不是直接返回 JSON 值。创建和 PUT 请求用 {value: ...} 包装；值可为对象、数组、null、布尔、数字或文本。公开 Bin 仅开放匿名当前及路径读取；列表、历史与写入仍需认证。','列表当前返回全部 items/total，不支持分页或服务端搜索参数。创建可传 name、description、visibility、collectionId、schemaId、schemaLocked、expiresAt；expiresAt 是未来 ISO 时间或 null。省略 visibility/expiresAt 使用服务端创建时的默认设置；显式 private/public/null 优先，默认变化不修改既有 Bin。']},
  {id:'history',title:'历史版本与元数据',introduction:['内容写入生成新的 JSON 版本；元数据更新不会生成 JSON 历史版本，但可能改变 ETag。历史恢复创建新版本，不改写旧版本。','元数据支持名称、描述、公开状态、集合、模型、模型锁、refreshSchema、数据锁和 expiresAt。locked 或 expiresAt 修改必须带 If-Match，其他元数据字段允许省略；示例统一建议带上。数据锁和模型锁是两种不同状态。']},
  {id:'etag',title:'ETag 与并发更新',introduction:['保留响应头 ETag 的完整值（包括引号）并发送 If-Match。每次独立写入重新读取 ETag，成功后旧值可能失效；412 时重新读取并处理冲突，不能自动覆盖或静默重试。','系统设置 PATCH 也必须携带设置 ETag。Bin 普通 PUT/DELETE 允许省略 If-Match；Merge Patch、路径 PUT、历史恢复、Collection/Schema 更新删除、回收站恢复/永久删除必须携带。批量永久删除使用 items[].etag。缺少必需 ETag 返回 428。','顺序入门示例会创建一个私有演示 Bin，并两次修改它。需要 bin:create、bin:read、bin:update。curl 顺序示例额外需要 Python 3 标准库解析 JSON；普通 curl 单请求无需 Python。']},
  {id:'paths',title:'PATCH 与 deep-path',introduction:['Merge Patch（RFC 7396）的 body 是补丁本身，不能包装 value。对象递归合并，null 删除对象字段，数组整体替换，非对象补丁替换整个 JSON。','路径先做 JSON Pointer 转义（~ → ~0、/ → ~1），再对每个 URL 段编码；例如 a/b → a~1b，x~y → x~0y。数组下标从 0 开始，最终 - 追加，父节点必须存在；最终对象字段可新建。/value 访问根 JSON。','以下 settings/theme 路径需要演示结构 {settings:{theme:"light"}}。实际 Bin 可能没有该父节点或不符合模型；先检查当前值，路径不存在为 404，模型校验失败为 422。']},
  {id:'collections',title:'Collection API',introduction:['集合支持名称/描述管理。移入或移出集合通过 Bin 的 collectionId 元数据；删除集合只解除归属，保留 Bin。更新和删除集合必须携带集合自己的 ETag。']},
  {id:'schemas',title:'Schema API',introduction:['支持 JSON Schema Draft 7，模型可以是对象或布尔值；只支持本地 JSON Pointer 引用，不获取远程引用。模型更新产生新修订，Bin 固定使用绑定修订；通过 refreshSchema 主动升级，模型锁需先单独解除。','validate 无论匹配与否都返回 HTTP 200，请检查 valid 和 issues；绑定模型的 Bin 写入不匹配返回 422。删除模型保留已有 Bin 的绑定修订。']},
  {id:'trash',title:'TTL 与回收站',introduction:['到期或删除后停止正常读写，进入回收站，保留至手动永久删除。每 15 分钟 Cron 标记过期项并续作已开始的永久删除，不按 30 天自动清空回收站。数据锁不延长 TTL。恢复需回收站快照 ETag，并清除旧 TTL。永久删除不可恢复。','批量永久删除只处理明确提供的 id/etag 快照，HTTP 200 仍须逐项检查 results[].status，不能视为全部成功。']},
  {id:'activity',title:'活动记录 API',introduction:['仅管理 Session 可读，显式 Authorization 返回 401 session_required。记录排除 Secret/JSON 内容，业务成功后尽力记录；故障可能缺少事件，不是完整审计链。','limit 默认 50、范围 1–100；action/resourceType 为枚举，cursor 绑定筛选。每请求最多扫描 1000 个对象、读取 40 个正文，可能返回空页；nextCursor 非 null 时继续。保留最新 2000 条，15 分钟 Cron 清理，短期可超出。']},
  {id:'system',title:'设置、导入与业务备份',introduction:[
    '系统管理仅接受登录 Session；任何 Authorization 都返回 401 session_required，即使 Cookie 有效。响应 no-store，写入校验 Origin。系统状态只做 R2 HEAD/KV GET；OAuth 状态表示配置齐全，不能证明登录、存储写入或 Cron 可用。统计最多扫描 10000 对象/读取 500 元数据，失败或超限显示不可用。',
    '设置 defaultVisibility 为 private/public，defaultTtlSeconds 为 null 或 1–31536000 整数秒。GET 返回 settings/etag；PATCH 只传要修改的默认字段并要求 If-Match，428 缺少、412 冲突。未设置时返回 private/null 虚拟 ETag，不写 R2。默认只用于省略的创建字段，相对 TTL 由服务器在创建时计算。',
    '普通导入 body 为 {items:[{name,value}]}，1–100 项；name 非空、最多 160 字符。每值序列化至多 1 MiB、深度 64，实际 UTF-8 正文至多 10 MiB。结构全量验证后顺序创建新 ID/版本 1；HTTP 200 必须检查 results 的 created/failed，不自动重试写入。数组/null/false 都是一个完整值，不按 format 字段解包。',
    '导出仅接受 scope=all|config&format=backup，或 scope=bin&id=<UUID>&format=value|backup；未知、重复或错误组合返回 400。value 是已保存当前 JSON。backup 为版本化 jsonbin-backup JSON，包含默认、集合、保留模型修订及版本、回收站/过期元数据和永久删除标记；config 仅包含默认设置及格式元数据，资源数组为空。每包最多 100 资源、250 逻辑对象、10 MiB JSON。缺文件/依赖/过渡状态为 409 backup_unavailable，导出中捕获资源改变为 backup_changed；新创建资源可能未被扫描。',
    'ZIP 由页面生成，仅 STORE 的 manifest.json/backup.json，CRC32 与 SHA-256 校验；最多 10 MiB + 64 KiB。Worker 不接收 ZIP 正文。系统凭据、API Keys/摘要、KV、活动、内部标记及未知命名空间不导出；业务 JSON 原样保留。旧协议当前不适用。',
    'restore body 为 {resource:{kind:collection|schema|bin|purged,data},dependencies:[{kind:collection|schema,id,fingerprint}]}，data 与备份一致，指纹为规范化 JSON 的 SHA-256。先恢复集合/模型，再发送引用 Bin。保留 ID/公开性/TTL/锁/删除状态及历史；既有/不同内容资源跳过而不覆盖。同包中断留隐藏 pending，可重试续作；已完成且未改动返回 unchanged。HTTP 200 检查 status 与 warnings；实际依赖变化可能为 409 restore_dependency_conflict。过期 Bin 立即进入回收站。',
    '设置不自动恢复，需另发 If-Match PATCH。恢复是逐资源发布，取消/网络错误不回滚已提交数据；先核对列表再重试。集合并发删除可能解除归属，清理失败仍保留 created 及 warning。示例恢复固定演示集合；替换数据和 ID 前先核对目标是否为空。',
  ]},
  {id:'errors',title:'错误码与恢复',introduction:['一般错误为 {error: "code"}；验证错误可有 issues，Scope 错误可有 requiredScopes。/auth/me 未登录为 {authenticated:false}，不能假设每个错误都存在 error。','全局 500 返回 internal_server_error，不返回内部异常。先检查 HTTP 状态，再读取对应接口的 JSON；网络错误不等同于业务一定未提交，写入重试前核对最新状态。']},
];
function op(id: string, sectionId: string, title: string, method: DocOperation['method'], path: string, scopes: readonly DocScope[], responseShape: string,
  body?: unknown, etag: DocOperation['etag'] = 'none', description = '', auth: DocOperation['auth'] = 'resource', successStatus = 200, publicRead = false): DocOperation {
  return {id,sectionId,title,method,path:'/api/v1'+path,scopes,responseShape,etag,description,auth,successStatus,publicRead,
    requestFields: body === undefined ? '无 JSON 请求体。路径参数见 URL；ID 使用资源 UUID。' : 'JSON 字段：' + (body !== null && typeof body === 'object' && !Array.isArray(body) ? Object.keys(body).join('、') : '补丁可为任意 JSON 值') + '。具体约束见本章说明和示例。', ...(body === undefined ? {} : {body})};
}
export const DOC_OPERATIONS: readonly DocOperation[] = [
  op('search-all','search','搜索全部资源','GET','/search?q=demo&type=all&limit=20',['bin:read','collection:read','schema:read'],'{items,nextCursor,source}'),
  op('search-bins','search','按集合或文本查找 Bin','GET','/search?q=demo&type=bin&limit=20',['bin:read','collection:read'],'{items,nextCursor,source}'),
  op('search-collections','search','搜索集合','GET','/search?q=demo&type=collection&limit=20',['collection:read'],'{items,nextCursor,source}'),
  op('search-schemas','search','搜索数据模型','GET','/search?q=demo&type=schema&limit=20',['schema:read'],'{items,nextCursor,source}'),
  op('search-index','search','索引状态','GET','/search/index',[],'{configured,available,current,builtAt,count}',undefined,'none','count 为最近构建的资源数，不是实时统计。','session'),
  op('search-rebuild','search','从 R2 重建索引','POST','/search/rebuild',[],'{configured,available,current,builtAt,count}',undefined,'none','可重试；并发变化返回 409，KV 未配置或暂不可用返回 503。','session'),
  op('auth-config','auth','登录方式配置','GET','/auth/config',[],'{passwordEnabled, githubEnabled}',undefined,'none','配置仅表明已配置登录方式。','none'),
  op('auth-login','auth','密码登录','POST','/auth/login',[],'{ok, user}',{username:'<USERNAME>',password:'<PASSWORD>'},'none','成功设置 Session Cookie；示例中的登录信息需要替换。','none'),
  op('auth-logout','auth','退出登录','POST','/auth/logout',[],'{ok}',undefined,'none','清除 Cookie。','session'),
  op('auth-me','auth','当前用户','GET','/auth/me',[],'{authenticated, user}',undefined,'none','未登录返回 401 {authenticated:false}。','session'),
  op('auth-github','auth','GitHub 登录入口','GET','/auth/github',[],'302 跳转到 GitHub',undefined,'none','在浏览器打开入口，授权后自动回调。callback 验证 code/state 并只允许配置的 GitHub 用户；不要手动重放 callback。','none',302),
  op('keys-list','keys','密钥列表','GET','/keys',[],'{items,total}',undefined,'none','不返回完整 Token 或摘要；revealable 表示是否可以重新查看完整值。','session'),
  op('keys-create','keys','创建 API Key','POST','/keys',[],'{key,token}',{name:'演示只读密钥',scopes:['bin:read'],expiresAt:null},'none','name 非空，scopes 至少一项且不得重复；expiresAt 为未来 ISO 时间或 null。创建响应直接返回 Token，并加密保存以供网页登录后再次查看。','session',201),
  op('keys-reveal','keys','查看完整 API Key','GET','/keys/{keyId}/token',[],'{token}',undefined,'none','仅管理 Session 可用。旧版本创建且没有加密明文的密钥返回 409 key_token_unavailable。','session'),
  op('keys-revoke','keys','撤销 API Key','DELETE','/keys/{keyId}',[],'{key}',undefined,'none','撤销后认证立即失效，但记录仍保留。','session'),
  op('keys-purge','keys','永久删除 API Key','DELETE','/keys/{keyId}/purge',[],'{ok,id}',undefined,'none','永久删除 R2 中的密钥记录及加密明文，不可恢复；有效、过期或已撤销密钥都可删除。','session'),
  op('bin-list','bins','列出数据仓','GET','/bins',['bin:read'],'{items,total}'),
  op('bin-create','bins','创建数据仓','POST','/bins',['bin:create'],'{meta,value,etag}',{name:'API 示例',value:DEMO_VALUE},'none','可选字段及未来 expiresAt 见本章说明。','resource',201),
  op('bin-get','bins','读取当前数据仓','GET','/bins/{binId}',['bin:read'],'{meta,value,etag}',undefined,'none','ETag、X-JSONBin-Version 位于响应头；公开当前读取可匿名。','resource',200,true),
  op('bin-put','bins','完整更新 JSON','PUT','/bins/{binId}',['bin:update'],'{meta,value,etag}',{value:DEMO_VALUE},'optional','建议携带 If-Match；成功创建新版本。'),
  op('bin-delete','bins','删除到回收站','DELETE','/bins/{binId}',['bin:delete'],'{ok}',undefined,'optional','删除后可在回收站恢复，示例建议携带 If-Match。'),
  op('bin-meta','history','修改元数据','PATCH','/bins/{binId}/meta',['bin:update'],'{meta,value,etag}',{description:'演示说明'},'conditional','修改 locked/expiresAt 必须携带 If-Match；其他字段建议携带。JSON 版本保持。'),
  op('history-list','history','版本列表','GET','/bins/{binId}/versions',['history:read'],'{items,currentVersion,total}'),
  op('history-get','history','读取历史版本','GET','/bins/{binId}/versions/{version}',['history:read'],'{id,version,createdAt,size,value,etag}'),
  op('history-restore','history','恢复历史为新版本','POST','/bins/{binId}/versions/{version}/restore',['bin:update','history:read'],'{meta,value,etag}',undefined,'required','使用当前 Bin 的 ETag，不能使用历史版本 ETag。'),
  op('bin-patch','paths','Merge Patch','PATCH','/bins/{binId}',['bin:update'],'{meta,value,etag}',{settings:{theme:'dark'}},'required'),
  op('bin-path-get','paths','读取 deep-path','GET','/bins/{binId}/value{path}',['bin:read'],'{id,path,value,etag,version}',undefined,'none','路径不存在返回 404。','resource',200,true),
  op('bin-path-put','paths','更新 deep-path','PUT','/bins/{binId}/value{path}',['bin:update'],'{meta,value,etag}',{value:'light'},'required','父节点必须存在；最终对象字段可创建。'),
  op('collection-list','collections','集合列表','GET','/collections',['collection:read'],'{items,total}'),
  op('collection-create','collections','创建集合','POST','/collections',['collection:write'],'{meta,etag}',{name:'API 演示集合',description:'演示'},'none','name 非空且最多 160 字符；description 最多 1000 字符。','resource',201),
  op('collection-get','collections','集合详情','GET','/collections/{collectionId}',['collection:read'],'{meta,etag,binCount}'),
  op('collection-bins','collections','集合成员','GET','/collections/{collectionId}/bins',['collection:read','bin:read'],'{items,total}'),
  op('collection-update','collections','更新集合','PATCH','/collections/{collectionId}',['collection:write'],'{meta,etag}',{name:'新集合名称'},'required'),
  op('collection-delete','collections','删除集合','DELETE','/collections/{collectionId}',['collection:write'],'{ok}',undefined,'required','保留成员 Bin，解除集合归属。'),
  op('schema-list','schemas','模型列表','GET','/schemas',['schema:read'],'{items,total}'),
  op('schema-create','schemas','创建模型','POST','/schemas',['schema:write'],'{meta,schema,etag}',{name:'API 演示模型',schema:{type:'object',properties:{count:{type:'integer'}},required:['count']}},'none','name 非空、schema 为 Draft 7 对象或布尔；description 可选。','resource',201),
  op('schema-get','schemas','读取模型','GET','/schemas/{schemaId}',['schema:read'],'{meta,schema,etag}'),
  op('schema-update','schemas','更新模型修订','PUT','/schemas/{schemaId}',['schema:write'],'{meta,schema,etag}',{name:'API 演示模型',schema:{type:'object'}},'required','提交完整 name/schema 和可选 description。'),
  op('schema-delete','schemas','删除模型','DELETE','/schemas/{schemaId}',['schema:write'],'{ok}',undefined,'required'),
  op('schema-validate','schemas','校验演示值','POST','/schemas/{schemaId}/validate',['schema:read'],'{valid,issues,revision}',{value:{count:'不是整数'}},'none','不匹配仍返回 HTTP 200，检查 valid:false。'),
  op('trash-list','trash','回收站列表','GET','/trash/bins',['bin:read'],'{items,total}'),
  op('trash-restore','trash','恢复回收站数据仓','POST','/trash/bins/{binId}/restore',['bin:update','history:read'],'{meta,value,etag}',undefined,'required','使用回收站快照 ETag；恢复内容及版本、清除旧 TTL。'),
  op('trash-purge','trash','永久删除数据仓','DELETE','/trash/bins/{binId}',['bin:delete'],'{ok}',undefined,'required','不可恢复；使用回收站快照 ETag。'),
  op('trash-batch','trash','批量永久删除','POST','/trash/bins/purge',['bin:delete'],'{results:[{id,status}]}',{items:[{id:'<BIN_ID>',etag:'<ETAG>'}]},'none','items 包含 1–100 个不重复 UUID 和非空 etag；逐项检查 status。'),
  op('system-info','system','读取系统信息','GET','/system/info',[],'{service,runtime,version,checkedAt,storage,oauth,statistics}',undefined,'none','探针和统计为只读；统计不可用时不返回部分总数。','session'),
  op('system-settings-get','system','读取默认设置','GET','/system/settings',[],'{settings,etag}',undefined,'none','保存响应的设置 ETag。','session'),
  op('system-settings-update','system','保存默认设置','PATCH','/system/settings',[],'{settings,etag}',{defaultVisibility:'private',defaultTtlSeconds:null},'required','示例会修改新建默认值；412 保留草稿并重新读取，不自动覆盖。','session'),
  op('system-import','system','批量导入完整 JSON 值','POST','/system/import',[],'{results:[{index,status,id?,error?}]}',{items:[{name:'演示 JSON',value:DEMO_VALUE},{name:'空值',value:null}]},'none','创建两个新 Bin；逐项检查 created/failed，网络失败先核对列表。','session'),
  op('system-export-all','system','导出全部业务备份','GET','/system/export?scope=all&format=backup',[],'jsonbin-backup schemaVersion:1 JSON',undefined,'none','下载响应为 JSON；ZIP 包装在浏览器完成。','session'),
  op('system-export-config','system','导出默认配置和元数据','GET','/system/export?scope=config&format=backup',[],'jsonbin-backup schemaVersion:1 JSON（无 Bin）',undefined,'none','仅默认设置及格式元数据，不含业务资源、认证凭据或 KV。','session'),
  op('system-export-bin','system','导出选定 Bin 含历史备份','GET','/system/export?scope=bin&id={binId}&format=backup',[],'jsonbin-backup schemaVersion:1 JSON',undefined,'none','含引用集合与模型；改 format=value 只返回保存的当前 JSON。','session'),
  op('system-restore','system','恢复一个演示集合','POST','/system/restore',[],'{kind,id,status,error?,warnings?}',{resource:{kind:'collection',data:{meta:{id:'22222222-2222-4222-8222-222222222222',name:'演示集合',description:'',slug:'collection-22222222',status:'active',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}}},dependencies:[]},'none','保留 ID；检查 created/unchanged/skipped/dependency_skipped/failed。不同既有资源不会被覆盖。','session'),
  op('activity-list','activity','活动列表','GET','/activity?limit=50',[],'{items,nextCursor,retentionLimit}',undefined,'none','action/resourceType/cursor 可选；错误或重复参数返回 400。','session'),
];
export const DOC_ERRORS: readonly DocError[] = [
  {status:400,code:'invalid_request / invalid_activity_query / invalid_oauth_state / invalid_query',meaning:'登录体、活动/导出查询或 OAuth state 无效。',recovery:'修正参数；OAuth 重新从入口登录。'},
  {status:401,code:'unauthorized / invalid_credentials / session_required',meaning:'登录或 Token 无效，或接口仅允许 Session。',recovery:'重新登录/检查 Token；管理接口不发送 Authorization。'},
  {status:403,code:'insufficient_scope / origin_not_allowed / github_user_not_allowed',meaning:'Scope、来源或 GitHub 用户不允许。',recovery:'检查 requiredScopes、应用 origin 或管理员配置。'},
  {status:404,code:'not_found / path_not_found',meaning:'资源不存在、已删除/到期，或路径不存在。',recovery:'检查 ID/父节点；删除或到期资源查看回收站。'},
  {status:409,code:'collection_deleting / collection_unavailable / collection_delete_conflict / schema_unavailable / bin_purging / version_missing / schema_revision_missing / key_update_conflict / version_limit_reached / revision_limit_reached / backup_changed / backup_unavailable / restore_conflict / restore_dependency_conflict / search_changed',meaning:'资源状态冲突或依赖不可用。',recovery:'刷新并检查依赖/回收站；已清理内容不能恢复。'},
  {status:412,code:'etag_conflict',meaning:'If-Match 已过期。',recovery:'重新读取最新 ETag，确认合并/覆盖后再提交。'},
  {status:413,code:'payload_too_large',meaning:'实际正文、业务值、备份对象数或字节超限。',recovery:'减少文件、资源或历史数量后重新预览；不靠伪造 Content-Length 绕过限制。'},
  {status:422,code:'validation_failed / invalid_json / invalid_path / invalid_version / patch_too_deep / invalid_schema / schema_validation_failed / schema_required',meaning:'请求字段、JSON、路径或模型不合法。',recovery:'修正 body/路径/版本/模型；issues 提供校验详情。'},
  {status:423,code:'bin_locked / schema_locked',meaning:'数据或模型绑定已锁定。',recovery:'单独解除对应锁后再提交；读取不受数据锁影响。'},
  {status:428,code:'precondition_required',meaning:'缺少必需 If-Match。',recovery:'读取该资源当前 ETag 并携带完整值。'},
  {status:500,code:'internal_server_error',meaning:'内部错误，可能已部分提交。',recovery:'稍后重读状态，写操作不盲目重复。'},
  {status:502,code:'github_token_exchange_failed / github_user_lookup_failed',meaning:'GitHub 网络、响应或 JSON 失败。',recovery:'稍后从登录入口重试。'},
  {status:503,code:'github_oauth_not_configured / key_service_unavailable / storage_unavailable / settings_unavailable / search_unavailable / search_index_unavailable / search_limit_exceeded / search_cleanup_limit_exceeded',meaning:'登录未配置、存储/搜索暂不可用，或扫描/清理超出单次上限。',recovery:'检查配置、稍后重试或减少资源；废弃索引清理可再次重建继续。'},
];
